/* Generated by tools/gen_theme_colors.py -- do not edit.
 * Regenerate with `make theme_colors.h` after changing theme.py.
 * Every number here also reaches voice_hud.py through theme.Ramp, and
 * tools/verify_voice_hud.py checks the two renderers still agree. */
#ifndef THEME_COLORS_H
#define THEME_COLORS_H

typedef struct {
    const char *name;
    rgb_t base, white, green, amber, title, value, alert;
} theme_colors_t;

static const theme_colors_t THEME_COLORS[] = {
    { "soft", {  120.0f,  161.0f,  221.0f }, {  210.0f,  226.0f,  250.0f }, {  120.0f,  230.0f,  160.0f }, {  250.0f,  200.0f,   90.0f }, {   96.0f,  128.0f,  175.0f }, {  130.0f,  175.0f,  240.0f }, {  240.0f,  130.0f,  110.0f } },
    { "hud", {  111.0f,  193.0f,  235.0f }, {  206.0f,  239.0f,  255.0f }, {   90.0f,  255.0f,  170.0f }, {  255.0f,  190.0f,   70.0f }, {   89.0f,  154.0f,  186.0f }, {  120.0f,  210.0f,  255.0f }, {  240.0f,  120.0f,   95.0f } },
    { "neon", {    1.0f,  216.0f,  157.0f }, {  163.0f,  248.0f,  224.0f }, {    0.0f,  240.0f,  170.0f }, {  255.0f,  200.0f,   80.0f }, {    2.0f,  171.0f,  125.0f }, {    0.0f,  235.0f,  170.0f }, {  255.0f,  110.0f,  110.0f } },
};
#define THEME_COLORS_N (sizeof THEME_COLORS / sizeof THEME_COLORS[0])

#endif

