#!/usr/bin/env python3
"""Emit theme_colors.h — the voice HUD's palettes, straight out of theme.py.

There are two voice HUD renderers: voice_hud.py, which is the readable one, and
voice_hud.c, which is the one that actually runs. They are held pixel-identical
by tools/verify_voice_hud.py, which means every colour has to exist twice and
agree exactly. Writing the C numbers by hand is how that stops being true — so
they are generated from the same theme.Ramp the Python asks at runtime, and the
Makefile regenerates the header before every build.

Levels, not colours: see theme.Ramp. 0 is the rim, 0.5 the accent, 1 white.

    python3 tools/gen_theme_colors.py > theme_colors.h
"""
from __future__ import annotations

import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path[:0] = [_HERE, os.path.dirname(_HERE)]       # repo layout and flattened Pi layout

import theme                                          # noqa: E402

def main() -> int:
    out = [
        "/* Generated by tools/gen_theme_colors.py -- do not edit.",
        " * Regenerate with `make theme_colors.h` after changing theme.py.",
        " * Every number here also reaches voice_hud.py through theme.Ramp, and",
        " * tools/verify_voice_hud.py checks the two renderers still agree. */",
        "#ifndef THEME_COLORS_H",
        "#define THEME_COLORS_H",
        "",
        "typedef struct {",
        "    const char *name;",
        "    rgb_t base, white, green, amber, title, value, alert;",
        "} theme_colors_t;",
        "",
        "static const theme_colors_t THEME_COLORS[] = {",
    ]
    for name in theme.ORDER:
        c = theme.hud_colours(name)
        fields = ", ".join(
            "{ %6.1ff, %6.1ff, %6.1ff }" % tuple(float(v) for v in c[k])
            for k in ("base", "white", "green", "amber", "title", "value", "alert"))
        out.append('    { "%s", %s },' % (name, fields))
    out += [
        "};",
        "#define THEME_COLORS_N (sizeof THEME_COLORS / sizeof THEME_COLORS[0])",
        "",
        "#endif",
        "",
    ]
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
